### ISSUE TITLE
Suggestion: Label Various OpenShift Envs (Dev, Prod etc.)

### ISSUE THREAD

**Issue by carlmes** [redhat-ai-services/rhoai-platform-foundation-bootcamp-instructions#25]
Students were struggling with identifying which OpenShift environment and web console they were logged onto. This was causing some confusion, especially with the labs that use multiple environments to demonstrate overlay concepts.

The suggestion it to add some banners to the environment provisioning pages, similar to:

```
apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: banner-data
spec:
  text: "This is the PROD environment"
  location: BannerTop
  backgroundColor: '#ff9900'
  color: '#000'
```

Each environment should have a unique name, and a different color to help the student to easily distinguish it.
